Prevent setup/update without Django dockerfile

diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -20,10 +20,11 @@ then
     then
         usage
     else
-        # Create Django dockerfile only if it doesn't exist
+        # Prevent setup and warn if Django dockerfile doesn't exist
         if [ ! -f ./src/django/docker-compose.env ]
         then
-            cp ./src/django/docker-compose.env.example ./src/django/docker-compose.env
+            echo "Missing Django dockerfile. Consult project README."
+            exit 1
         fi
 
         # Build the angular container image.
